version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: server-monitor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_pass
      POSTGRES_DB: server_monitor
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor_user -d server_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
